import type { AppData } from '@/types';

export const DEFAULT_DATA: AppData = {
    slides: [
        {
            title: 'آرتام سازه',
            kicker: 'گروه توسعه و ساختمان',
            desc: 'ساخت امروز، سرمایه‌گذاری برای فردا',
            manager: 'مدیریت: مهندس حمید جاهد',
            btn1Text: 'مشاهده پروژه‌ها',
            btn1Link: '#projects',
            btn2Text: 'درخواست مشاوره',
            btn2Link: '#contact',
            image: '/images/slide/1.jpg',
            order: 0,
            active: true,
        },
        {
            title: 'ساخت ارزش',
            kicker: 'معماری و توسعه',
            desc: 'طراحی مدرن، اجرای دقیق، سرمایه‌گذاری مطمئن',
            manager: 'با تیمی متخصص و متعهد',
            btn1Text: 'پروژه‌های شاخص',
            btn1Link: '#projects',
            btn2Text: 'ارتباط با ما',
            btn2Link: '#contact',
            image: '/images/slide/2.jpg',
            order: 1,
            active: true,
        },
        {
            title: 'آینده‌ای مطمئن',
            kicker: 'سرمایه‌گذاری ساختمانی',
            desc: 'با تحلیل دقیق بازار و مدیریت هوشمند پروژه',
            manager: 'همراه با شما در تمام مراحل',
            btn1Text: 'خدمات ما',
            btn1Link: '#services',
            btn2Text: 'مشاوره رایگان',
            btn2Link: '#contact',
            image: '/images/slide/3.jpg',
            order: 2,
            active: true,
        },
    ],
    projects: [
        {
            name: 'آرتام نیاوران',
            location: 'نیاوران',
            status: 'در حال ساخت',
            progress: 75,
            image: '/images/projects/1.jpg',
            description: 'پروژه آپارتمانی لوکس در نیاوران با نمای مدرن و امکانات کامل.',
        },
        {
            name: 'پروژه زعفرانیه',
            location: 'زعفرانیه',
            status: 'در حال ساخت',
            progress: 40,
            image: '/images/projects/2.jpg',
            description: 'ساختمان ۸ واحدی در منطقه زعفرانیه با طراحی منحصربه‌فرد.',
        },
        {
            name: 'آرتام فرشته',
            location: 'فرشته',
            status: 'تحویل شده',
            progress: 100,
            image: '/images/projects/3.jpg',
            description: 'پروژه مشارکتی در فرشته با ۶ واحد ۲۰۰ متری و امکانات هوشمند.',
        },
        {
            name: 'مدرن ولنجک',
            location: 'ولنجک',
            status: 'تحویل شده',
            progress: 100,
            image: '/images/projects/4.jpg',
            description: 'ساختمان مدرن در ولنجک با ۱۰ واحد و فضای سبز اختصاصی.',
        },
    ],
    services: [
        {
            title: 'مدیریت و توسعه پروژه',
            icon: 'bi-buildings',
            desc: 'مدیریت حرفه‌ای پروژه‌های ساختمانی از ایده تا تحویل',
        },
        {
            title: 'طراحی و اجرای ساختمان',
            icon: 'bi-rulers',
            desc: 'طراحی معماری مدرن و اجرای دقیق با بالاترین استانداردها',
        },
        {
            title: 'سرمایه‌گذاری ساختمانی',
            icon: 'bi-coin',
            desc: 'تحلیل دقیق بازار و شناسایی بهترین فرصت‌های سرمایه‌گذاری',
        },
        {
            title: 'مشارکت در ساخت',
            icon: 'bi-hand-thumbs-up',
            desc: 'مدل‌های شفاف مشارکت با حفظ منافع طرفین',
        },
    ],
    testimonials: [
        {
            name: 'رضا احمدی',
            title: 'سرمایه‌گذار',
            text: 'کیفیت ساخت و ساز و دقت در اجرا واقعاً تحسین‌برانگیز بود.',
            status: 'approved',
            rating: 5,
            date: '۱۴۰۵/۰۵/۰۱',
        },
        {
            name: 'سارا محمدی',
            title: 'مالک پروژه',
            text: 'پروژه مشارکت در ساخت ما به بهترین شکل ممکن انجام شد.',
            status: 'approved',
            rating: 5,
            date: '۱۴۰۵/۰۵/۰۲',
        },
        {
            name: 'علی کریمی',
            title: 'مدیرعامل',
            text: 'از مشاوره اولیه تا تحویل نهایی، حس اطمینان و حرفه‌ای بودن را به ما منتقل کردند.',
            status: 'pending',
            rating: 5,
            date: '۱۴۰۵/۰۵/۰۳',
        },
    ],
    blogs: [
        {
            title: 'روندهای جدید در معماری پایدار',
            category: 'معماری و ساخت',
            date: '۱۴۰۵/۰۵/۲۸',
        },
        {
            title: 'تحلیل جامع بازار سرمایه‌گذاری ساختمانی',
            category: 'سرمایه‌گذاری',
            date: '۱۴۰۵/۰۵/۲۰',
        },
        {
            title: 'مدیریت هزینه‌ها در پروژه‌های بزرگ',
            category: 'مدیریت پروژه',
            date: '۱۴۰۵/۰۵/۱۰',
        },
    ],
    settings: {
        brand: 'ARTAM SAZEH',
        subBrand: 'گروه توسعه و ساختمان آرتام سازه',
        phone: '۰۹۱۲۲۵۹۵۹۴۴',
        email: 'info@artamsazeh.com',
        address: 'تهران - تمام مناطق',
        footer: '© ۱۴۰۵ - تمامی حقوق این وب‌سایت متعلق به گروه توسعه و ساختمان آرتام سازه است.',
    },
    consultations: [],
    admins: [
        {
            fullName: 'مدیر سیستم',
            username: 'admin',
            password: 'hashed_password_will_be_generated_by_seed',
            role: 'full',
            phone: '09122595944',
            permissions: ['slides', 'projects', 'services', 'testimonials', 'blog', 'consultations'],
        },
    ],
};